### ISSUE TITLE
libCGAL not found on OSX

### ISSUE THREAD

**Issue by cedelmaier** [LLNL/MemSurfer#20]
I'm attempting to install MemSurfer via the online instructions, and wound up with a problem when I attempt to actually run the installation script. I installed CGAL via homebrew, however, this is a header-only library, and so when I try to setup MemSurfer I get the following error:
```
  > MemSurfer = (/Users/cedelmaier/Projects/Biophysics/MemSurfer)
  > CGAL_ROOT = (/usr/local/Cellar/cgal/5.4/)
  > EIGEN_ROOT = (/usr/local/Cellar/eigen/3.4.0_1/)
  > BOOST_ROOT = (/usr/local/Cellar/boost/1.78.0_1/)
Traceback (most recent call last):
  File "/Users/cedelmaier/Projects/Biophysics/MemSurfer/setup.py", line 160, in <module>
    PATHS = fetch_paths(os.path.join(PATH_MEM, 'external'))
  File "/Users/cedelmaier/Projects/Biophysics/MemSurfer/setup.py", line 106, in fetch_paths
    paths['cgal'].update({'lib': find_shlib_path(paths['cgal']['root'], 'libCGAL')})
  File "/Users/cedelmaier/Projects/Biophysics/MemSurfer/setup.py", line 63, in find_shlib_path
    raise Exception(f'Find_shlib_path({path},{libname}) failed!')
Exception: Find_shlib_path(/usr/local/Cellar/cgal/5.4/,libCGAL) failed!
```

So really, need to know if the library is really needed, or change the installation instructions for the brew installation version to accommodate the different installation types.

**Comment by bhatiaharsh** [comment]
i have not tested this with a header-only version of cgal (i didnt know it existed). if this had to work, you would need to compile the cgal code into memsurfer library.. could be done but likely more work..

I would suggest installing cgal with the dynamic library, and then linking memsurfer against it. CGAL is absolutely needed and not optional.

**Comment by cedelmaier** [comment]
Okay, thank you for answering the question! I'll install CGAL and see how it goes for my project. Thanks!

**Comment by zrollins** [comment]
Any success with this? I am having a similar issue.
