### ISSUE TITLE
installation: import issue

### ISSUE THREAD

**Issue by andreashlarsen** [LLNL/MemSurfer#24]
Hi,

I have installed Memsurfer 1.1.0. 
setup.py ran successfully. But when testing with a simple script "test_install.py", containing just one line:

import memsurfer

then I get the error:

Traceback (most recent call last):
  File "test_install.py", line 1, in <module>
    import memsurfer
  File "/usr/local/lib/python3.8/dist-packages/memsurfer-1.1.0-py3.8-linux-x86_64.egg/memsurfer/__init__.py", line 15, in <module>
    from .membrane import Membrane
  File "/usr/local/lib/python3.8/dist-packages/memsurfer-1.1.0-py3.8-linux-x86_64.egg/memsurfer/membrane.py", line 20, in <module>
    from . import memsurfer_cmod
  File "/usr/local/lib/python3.8/dist-packages/memsurfer-1.1.0-py3.8-linux-x86_64.egg/memsurfer/memsurfer_cmod.py", line 13, in <module>
    from . import _memsurfer_cmod
ImportError: /usr/local/lib/python3.8/dist-packages/memsurfer-1.1.0-py3.8-linux-x86_64.egg/memsurfer/_memsurfer_cmod.so: undefined symbol: __gmpq_add

notes and related issues: 
- the error is similar to issue #3, but the setup.py file has been changed since, so the solution cannot be applied.
- This issue might be essentially the same as issue #12 , which is unsolved. 
- I read issue https://github.com/LLNL/MemSurfer/issues/23, and have ensured that I was not in the source dir when trying to import memsurfer
- OS version: Ubuntu 20.04
- python version: 3.8.10

kind regards, 
Andreas

**Comment by andreashlarsen** [comment]
ps. I read issue #23, and have ensured that I was not in the source dir.

**Comment by piosto** [comment]
I've got exactly the same issue: 

ImportError: /home/piosto/miniconda3/lib/python3.9/site-packages/memsurfer-1.1.0-py3.9-linux-x86_64.egg/memsurfer/_memsurfer_cmod.so: undefined symbol: __gmpq_add

Ubuntu 22.04
python 3.9
gmp 6.2.1 

Kind regards,
Piotr

**Comment by askusay** [comment]
Same issue here 

ImportError: /home/software/miniconda3/envs/memsurfer/lib/python3.9/site-packages/memsurfer-1.1.0-py3.9-linux-x86_64.egg/memsurfer/_memsurfer_cmod.so: undefined symbol: __gmpq_add

Ubuntu 22.04
python 3.9
gmp 6.2.1

Would really appreciate a fix to this, 

Kind regards,
Ali

**Comment by nambiarnik** [comment]
Hi I've got the same error.
ImportError: /home/nambinik/miniconda3/lib/python3.11/site-packages/memsurfer-1.1.0-py3.11-linux-x86_64.egg/memsurfer/_memsurfer_cmod.so: undefined symbol: __gmpq_add

It seems that the gmp library path needs to be added in setup.py. Did anyone find a solution to this problem?
