### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by vaneerdf** [LLNL/MemSurfer#25]
Hello,

I am trying to install MemSurfer on Ubuntu 22.04
The installation of all dependencies goes well, however `setup.py` fails with `TypeError: _is_gcc() takes 1 positional argument but 2 were given`.

Help is much appreciated

```
(base) ➜  MemSurfer git:(develop) echo $CC
/usr/bin/gcc-7
(base) ➜  MemSurfer git:(develop) echo $CXX
/usr/bin/g++-7
(base) ➜  MemSurfer git:(develop) echo $LDCXXSHARED
/usr/bin/g++-7 -bundle -undefined dynamic_lookup
(base) ➜  MemSurfer git:(develop) python --version
Python 3.7.12

(base) ➜  MemSurfer git:(develop) python setup.py install
> Installing MemSurfer for (floris) on (ika) (platform=linux)
  > MemSurfer = (/home/floris/MemSurfer)
  > CGAL_ROOT = (/home/floris/MemSurfer/external)
  > EIGEN_ROOT = (/home/floris/MemSurfer/external)
  > BOOST_ROOT = (/home/floris/MemSurfer/external)
running install
/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing memsurfer.egg-info/PKG-INFO
writing dependency_links to memsurfer.egg-info/dependency_links.txt
writing requirements to memsurfer.egg-info/requires.txt
writing top-level names to memsurfer.egg-info/top_level.txt
reading manifest file 'memsurfer.egg-info/SOURCES.txt'
adding license file 'LICENSE'
adding license file 'NOTICE'
writing manifest file 'memsurfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 252, in <module>
    cmdclass={'build_py': CustomBuildPy, 'build_ext': CustomBuildExt}
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_py')
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "setup.py", line 137, in run
    self.run_command("build_ext")
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/floris/miniconda3/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "setup.py", line 122, in build_extensions
    if not self.compiler._is_gcc(compiler_name):
TypeError: _is_gcc() takes 1 positional argument but 2 were given
```

**Comment by askusay** [comment]
Hi Palaou, not sure if you are still looking for a solution, since you seem to be using gcc, it should be safe to comment out the lines in `setup.py` causing this error:
`#if not self.compiler._is_gcc(compiler_name):`
`#   raise Exception(f'Need a GCC compiler. Found ({compiler_name})')`

This solved it for me

**Comment by vaneerdf** [comment]
@askusay Thanks a lot for your help! I did not manage to install it, so I really appreciate your help!
